### ISSUE TITLE
Why `standardx` as a dependency?

### ISSUE THREAD

**Issue by spl** [AuroraDigital/eslint-config-aurora#4]
I'm just wondering why use `standardx` as a dependency in your `package.json`. Does it pull in more transitive/indirect dependencies than necessary? Thanks!

**Comment by spl** [comment]
I think this package could replace one that I was thinking about creating. So, if you want PRs to help with the dependencies or other things, I can do that.

**Comment by pfcodes** [comment]
> I'm just wondering why use `standardx` as a dependency in your `package.json`. Does it pull in more transitive/indirect dependencies than necessary? Thanks!

Went with `standardx` because the docs pitched it as a way to use `standard` as a base with a few tweaks without having to _configure hundreds of ESLint rules individually_ with `eslint-config-standard`

<img width="804" alt="image" src="https://user-images.githubusercontent.com/26803762/84834587-95df4e00-afe6-11ea-8ceb-354c6ddf5fec.png">


> I think this package could replace one that I was thinking about creating. So, if you want PRs to help with the dependencies or other things, I can do that.

For sure, feel free. There's a sister Prettier package that works in tandem with this one that could use some help too @spl

**Comment by spl** [comment]
> Went with `standardx` because the docs pitched it as a way to use `standard` as a base with a few tweaks without having to _configure hundreds of ESLint rules individually_ with `eslint-config-standard`

Oh, right, of course. I think that makes sense.

The only thing is, as far as I understand it, if I want to use `eslint-config-aurora` as a shareable config with (a) `eslint` alone or (b) `standard` instead of `standardx` or (c) some other `eslint`-based scheme, then, by depending on `eslint-config-aurora` now, I get `standardx` whether I want it or not, because it's a dependency of `eslint-config-aurora`. I think that (a) `eslint-config-aurora` should probably depend only on `eslint-config-standard` and (b) the “user” of `eslint-config-aurora` should then depend on `standardx` or whatever. Does that sound right?

> There's a sister Prettier package that works in tandem with this one that could use some help too

👍
